### ISSUE TITLE
Torch and CUDA versions cannot be found

### ISSUE THREAD

**Issue by GANZI101** [i3eaa/Imperial-Aim-Assist#2]
sorry if this is a obvious fix, I don't know anything about programming so please be considerate
![Capture](https://github.com/i3eaa/Imperial-Aim-Assist/assets/142658675/9930a839-5c60-476c-89b1-aecdf5e35b5b)

**Comment by i3eaa** [comment]
hello, all you have to do is find the version of torch in the requirements.txt file. Uninstall torch and then reinstall it. Hope this helps
